service: koala-challenge
plugins:
  - serverless-s3-sync

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

custom:
  s3Sync:
    - bucketName: koala.kana.dev
      localDir: dist

resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: koala.kana.dev
